version: "3"


services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=6500
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies-catalog_db

volumes:
  database-data: {}
