version: "3"

services:
  database:
    container_name: mongo 
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=waproject
      - MONGO_INITDB_ROOT_PASSWORD=challenge
      - MONGO_INITDB_DATABASE=movies-catalog_db
  api:
    container_name: api
    restart: always
    build:
      context: .
    depends_on:
      - database
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: npm start
  
volumes:
  database-data: {}
