version: "3"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    restart: always
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=docker
      - PG_DB=movies_catalog-db
    volumes:
      - ./data:/data/db
    ports:
      - 5432
  api:
    container_name: movies-catalog-api
    build:
      context: .
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./:/home/node/app
    env_file:
      - .env
    command: npm run start
