version: "3"

services:
  database:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=waproject
      - MONGO_INITDB_ROOT_PASSWORD=challenge
      - MONGO_INITDB_DATABASE=movies-catalog_db

volumes:
  database-data: {}
